### ISSUE TITLE
Add site.type property

### ISSUE THREAD

**Issue by vdias38** [meumobi/ion-ams-report#100]
### Expected behaviour
Add new site.type property with available values {MarketPlace, Premium}
Migrate all sites and default value of site.type as 'MarketPlace'

**Comment by danconte72** [comment]
- [x] add 'type' field on model;
- [x] add 'type' field on site-details, use ion-select, options  {MarketPlace, Premium} , default 'MarketPlace';
- [x] set all 'sites' type as 'MarketPlace', use `firebase/tools/index`

**Comment by danconte72** [comment]
> Migrate all editors and default value of site.type as 'MarketPlace'

Is it correct? Migrate all editors? Or migrate all sites?

**Comment by danconte72** [comment]
script to set type for all sites
```js
firebase.initializeApp(config);

var ref = firebase.database().ref('/');
ref.child('sites').on('value', function(snap){
  var updates = {};
  Object.keys(snap.val()).forEach(element => {
    console.log(element);
    updates['/sites/' + element + '/type'] = 'MarketPlace';
  });
  ref.update(updates);
})
```
