### ISSUE TITLE
Mix Premium and MarketPlace Results if site.type is 'MarketPlace'

### ISSUE THREAD

**Issue by vdias38** [meumobi/ion-ams-report#102]
Display mixed results as MarketPlace. BUT:
- Premium reports have no 'impr. reçues' then sum of impr. reçues from Premium and AMS MP would lead to 'NaN' (Not a Number). And by extension fillRate and discrepencies also.
- Partner value for premium is always 'adtech'
- On reports list of all sites page (only available for admin) reports remains as current version, without mix.
- Add column 'Announcers' for admin on MarketPlace Report

**Comment by danconte72** [comment]
investigate if site.type is MarketPlace could "concat" Premium data as 'AMS Market Place'

**Comment by danconte72** [comment]
- [x] if site.type is MarketPlace could "concat" Premium data as 'AMS Market Place'

**Comment by danconte72** [comment]
should check if data structure for any inventory type is the same

**Comment by danconte72** [comment]
data keep the same structure
```js
["annonceur", "campagne", "date", "emplacement", "format", "impressions envoyees", "impressions facturables", "impressions prises", "impressions reçues", "inventaire", "key", "marge", "partenaire", "position", "revenu", "revenu net", "site", "uid"]
```
