### ISSUE TITLE
Prevent access to child pages if not logged

### ISSUE THREAD

**Issue by vdias38** [meumobi/ion-ams-report#26]
https://dashboard.admysports.com/#/editors always open /editors page after redirect from login

**Comment by vdias38** [comment]
Sample Code Usage For ionViewCanEnter() Ionic Page Lifecycle Function:

```
ionViewCanEnter(): boolean {
    if(userIsLoggedIn){
      return true;
    } else {
      return false;
    }
  }
```

**Comment by vdias38** [comment]
There's a bug on ionic [NavGuards with ionic-angular 3.5.0 has a breaking change](https://github.com/ionic-team/ionic/issues/12193)that prevent to dispatch request

**Comment by mburger81** [comment]
Was you able to found a workaround for this?

**Comment by vdias38** [comment]
@mburger81 to be honest I didn't search, waiting for bug fix from Ionic team.

**Comment by mburger81** [comment]
I think there would never be a fix for this.

But how are you handling now page guards and user authentication? You probably used a workaround. Perhaps we can share some implementations or somethink like best practice?

**Comment by vdias38** [comment]
> i don't see how to trigger a redirect other than using setTimeout to put the redirect last in the js event loop:
```js
  ionViewCanEnter() {
    console.log('Can enter.');
    setTimeout(() => {
      this.navCtrl.setRoot(Page2)
    }, 0);
    return false;
  }
```

Source: https://www.bountysource.com/issues/32898369-missing-canactivate-resolve-functionality-in-ionic2
