### ISSUE TITLE
add new report fields Gross revenue and Gross cpm

### ISSUE THREAD

**Issue by vdias38** [meumobi/ion-ams-report#48]

**Comment by vdias38** [comment]
I've deployed updates on AMS.Connect, adding fields 'revenu net' and 'marge' on AMS Format. I've also [commit on ion-ams-report](https://github.com/meumobi/ion-ams-report/commit/6483f4a928e217fbf71631fae062516d18624aa7) an update to add column 'Net Revenues' (part of this issue).
You need to add 'CPM' with scope=editor, admin and rename old CPM to 'Gross CPM'.

**Comment by danconte72** [comment]
What have to be showed  when reading 'old reports'? Without 'revenu net' and 'marge'.
