### ISSUE TITLE
on iOS sites-list is empty

### ISSUE THREAD

**Issue by vdias38** [meumobi/ion-ams-report#73]
Tested on iPod, iOS 9.3.5
works well on Android. Sites appear if type a search
![img_1100](https://user-images.githubusercontent.com/9011612/32066308-3c4cfbec-ba77-11e7-8bb0-7c22c5c7004b.PNG)

**Comment by danconte72** [comment]
Works on iOS 11.0.3 - iPhone 6s
![img_571e243d9633-1](https://user-images.githubusercontent.com/32454870/32101514-3b539ef0-baf7-11e7-8b2c-2512c5987247.jpeg)
