### ISSUE TITLE
on iOS logo+title on sidemenu header are too tiny

### ISSUE THREAD

**Issue by vdias38** [meumobi/ion-ams-report#74]
![img_1101](https://user-images.githubusercontent.com/9011612/32066517-f86037ea-ba77-11e7-90e2-32a8273362d2.PNG)

**Comment by danconte72** [comment]
This issue is not re-produceable on iOS 11.0.3 - iPhone 6s
![img_ef96868ab3fc-1](https://user-images.githubusercontent.com/32454870/32101283-58b42b32-baf6-11e7-9299-2df23f829e84.jpeg)
