### ISSUE TITLE
on iOS login form background disappear when focus on input

### ISSUE THREAD

**Issue by vdias38** [meumobi/ion-ams-report#75]
![img_1102](https://user-images.githubusercontent.com/9011612/32066563-1b87a014-ba78-11e7-8dca-e131bef33fbe.PNG)

**Comment by danconte72** [comment]
This issue is not re-produceable on iOS 11.0.3 - iPhone 6s
![img_0278 trim](https://user-images.githubusercontent.com/32454870/32101074-74e60ab0-baf5-11e7-9ef2-91386b3c4818.gif)
