### ISSUE TITLE
When user is created none authentication record is added

### ISSUE THREAD

**Issue by vdias38** [meumobi/ion-ams-report#98]
The bug was observed on PROD for following account created this morning

![ams_report_-_prod_ _database_ _firebase_console](https://user-images.githubusercontent.com/9011612/37203603-21440688-2386-11e8-9e24-73e108c905f9.png)

### Expected behaviour
Tell us what should happen

### Actual behaviour
If you create a new user on dashboard, authentication record is not created, then user can't log in

### Steps to reproduce
1. create new user for existing editor
2. try to log in with its account
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
There is a cloud function wrote to do this, but has not any execution log (Cf logs visible on console.firebase were from the past week only)
- check if cf is correctly set and triggered

**Comment by danconte72** [comment]
- I've tested and the cf has been not triggered;
- createUser is enabled on [GCP](https://console.cloud.google.com/functions/list?project=ams-report&folder&organizationId) 
![image](https://user-images.githubusercontent.com/32454870/50005659-456ed680-ff92-11e8-8db2-2925366f89fe.png)

**Comment by danconte72** [comment]
- the latest logs about createUser cf is [here](https://console.cloud.google.com/logs/viewer?project=ams-report&folder&organizationId&resource=cloud_function%2Ffunction_name%2FcreateUser%2Fregion%2Fus-central1&minLogLevel=0&expandAll=false&timestamp=2018-12-14T13:30:17.928000000Z&customFacets=&limitCustomFacetWidth=true&interval=NO_LIMIT&scrollTimestamp=2018-03-09T18:49:41.327000000Z)
![image](https://user-images.githubusercontent.com/32454870/50006288-6a644900-ff94-11e8-9871-65e9f9c410a4.png)
 

the errors  found were

```
@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":13,"message":"Error setting up the execution environment for your function. Please try again after a few minutes.
```
some answers point for a [deploy](https://stackoverflow.com/questions/45745764/gcloud-cloud-functions-deployment-failure-code-13-message-failure-in-the-executi) problem

**Comment by danconte72** [comment]
The last [changes](https://github.com/meumobi/ion-ams-report/commit/8e1198987dbbe22e6558199cda1adfe1ee00e3a4) on cf were did on Jan 10th, 2 months before last log

**Comment by danconte72** [comment]
I've add logs to track  cf call/execution and deployed on int env

**Comment by danconte72** [comment]
to deploy only functions on firebase 
```bash
$ firebase deploy --only functions
```
