### ISSUE TITLE
Realtime Database 'ams-report' has insecure rules

### ISSUE THREAD

**Issue by vdias38** [meumobi/ion-ams-report#99]
### Actual behaviour
issue(s) with your security rules:
- any user can read your entire database
- any user can write to your entire database

**Comment by danconte72** [comment]
should update [security rules](https://console.firebase.google.com/u/0/project/ams-report/database/ams-report/rules) allowing  
write and read for authenticated users: 
- [filtering by user id](https://firebase.google.com/docs/database/security/user-security?authuser=0#section-structuring-db) 
- [all users](https://firebase.google.com/docs/database/security/resolve-insecurities?authuser=0#access_for_any_authenticated_user) 

should check how to AMS.Connect write data on realtime database

**Comment by danconte72** [comment]
should check php sdk auth for ams.connect

**Comment by danconte72** [comment]
### how to check if project writes with security rules applied 
- clone ams.connect
- up a ams.connect instance pointing to ams-report int
  creating a .env file with FIREBASE_CONFIG_PATH="ams-report-test-firebase-adminsdk-z0qg1-c777197914.json"
- update ams-report int rules to demand authenticated access
```js
{
  "rules": {
      // any logged-in user access your data
      ".read": "auth !== null",
      ".write": "auth !== null"
   }
}
```
- run ams.connect commands 
?? I didn't find

**Comment by danconte72** [comment]
After update rules, access (CRUD) through UI is working properly

**Comment by danconte72** [comment]
I've tested on ams-connect int env and accessing ```providers/perform/``` route, it performed and and add data on ams-report-int

**Comment by danconte72** [comment]
I've update security rules on prod to 
```js
{
  "rules": {
      // any logged-in user access your data
      ".read": "auth !== null",
      ".write": "auth !== null"
   }
}
```
